import { Recipe } from "@/types/recipes";

export const recipeCategories = [
  "Quick",
  "Vegetarian",
  "Vegan",
  "High Protein",
  "Low Carb",
  "Breakfast",
  "Lunch",
  "Dinner",
  "Gluten Free",
  "Dairy Free",
  "Budget",
  "Kid-Friendly",
  "Pescatarian",
] as const;

export const recipes: Recipe[] = [
  {
    id: "salmon-garlic-butter",
    title: "Garlic Butter Salmon",
    description:
      "Flaky salmon fillets seared in a garlicky butter sauce with lemon and herbs.",
    time: 20,
    img: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?q=80&w=1200&auto=format&fit=crop",
    tags: ["Pescatarian", "Low Carb", "Dinner", "Quick"],
    cuisine: "American",
    difficulty: "Easy",
    servings: 2,
    rating: 4.7,
    nutrients: { calories: 520, protein: 38, carbs: 2, fat: 40 },
    dietary: { pescatarian: true, lowCarb: true, glutenFree: true },
    ingredients: ["salmon", "butter", "garlic", "lemon", "parsley"],
    instructions: [
      "Pat salmon dry and season with salt and pepper.",
      "Melt butter in skillet, add garlic until fragrant.",
      "Sear salmon 3-4 min per side.",
      "Finish with lemon juice and parsley.",
    ],
    premium: false,
    allergens: ["Fish"],
    notIncluded: ["Olive Oil", "Salt", "Black Pepper"],
    utensils: ["Skillet", "Tongs", "Knife"],
    nutrientsExtra: { saturatedFat: 19, sugar: 0, fiber: 0, cholesterolMg: 120, sodiumMg: 320 },
  },
  {
    id: "avocado-chicken-wrap",
    title: "Avocado Chicken Wrap",
    description:
      "Juicy chicken, creamy avocado, crunchy veg—perfect high-protein grab-and-go lunch.",
    time: 15,
    img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop",
    tags: ["High Protein", "Lunch", "Quick"],
    cuisine: "American",
    difficulty: "Easy",
    servings: 1,
    rating: 4.5,
    nutrients: { calories: 430, protein: 36, carbs: 28, fat: 20 },
    dietary: { highProtein: true },
    ingredients: ["chicken", "avocado", "tortilla", "lettuce", "tomato"],
    instructions: [
      "Slice cooked chicken and avocado.",
      "Warm tortilla and layer lettuce, tomato, chicken, avocado.",
      "Season and roll tight; slice in half.",
    ],
    premium: false,
    allergens: ["Wheat"],
    notIncluded: ["Salt", "Black Pepper"],
    utensils: ["Knife", "Cutting Board"],
    nutrientsExtra: { saturatedFat: 6, sugar: 3, fiber: 6, cholesterolMg: 85, sodiumMg: 520 },
  },
  {
    id: "veggie-power-bowl",
    title: "Veggie Power Bowl",
    description:
      "Roasted vegetables, quinoa, and tahini dressing for a hearty vegetarian bowl.",
    time: 25,
    img: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=1200&auto=format&fit=crop",
    tags: ["Vegetarian", "High Fiber", "Dinner"],
    cuisine: "Mediterranean",
    difficulty: "Easy",
    servings: 2,
    rating: 4.6,
    nutrients: { calories: 540, protein: 18, carbs: 68, fat: 20 },
    dietary: { vegetarian: true },
    ingredients: ["quinoa", "sweet potato", "chickpeas", "spinach", "tahini"],
    instructions: [
      "Roast diced sweet potato and chickpeas 20 min at 425°F (220°C).",
      "Cook quinoa per package.",
      "Whisk tahini, lemon, water, garlic.",
      "Assemble with spinach and drizzle dressing.",
    ],
    premium: false,
    allergens: [],
    notIncluded: ["Salt", "Olive Oil", "Black Pepper"],
    utensils: ["Baking Sheet", "Medium Bowl"],
    nutrientsExtra: { saturatedFat: 3, sugar: 14, fiber: 11, cholesterolMg: 0, sodiumMg: 380 },
  },
  {
    id: "berry-yogurt-parfait",
    title: "Berry Yogurt Parfait",
    description:
      "Layers of Greek yogurt, fresh berries, and crunchy granola—breakfast in 10.",
    time: 10,
    img: "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1200&auto=format&fit=crop",
    tags: ["Breakfast", "Quick"],
    cuisine: "American",
    difficulty: "Easy",
    servings: 1,
    rating: 4.3,
    nutrients: { calories: 320, protein: 18, carbs: 42, fat: 9 },
    dietary: { vegetarian: true },
    ingredients: ["yogurt", "berries", "granola", "honey"],
    instructions: [
      "Layer yogurt, berries, granola in a glass.",
      "Drizzle with honey and serve.",
    ],
    premium: false,
    allergens: ["Milk"],
    notIncluded: [],
    utensils: ["Spoon", "Glass"],
    nutrientsExtra: { saturatedFat: 3, sugar: 26, fiber: 4, cholesterolMg: 15, sodiumMg: 90 },
  },
  {
    id: "chickpea-curry",
    title: "Creamy Chickpea Curry",
    description:
      "Comforting coconut tomato curry with tender chickpeas—naturally vegan and filling.",
    time: 35,
    img: "https://images.unsplash.com/photo-1625944528520-bd61234f2337?q=80&w=1200&auto=format&fit=crop",
    tags: ["Dinner", "Budget"],
    cuisine: "Indian",
    difficulty: "Medium",
    servings: 4,
    rating: 4.8,
    nutrients: { calories: 460, protein: 16, carbs: 60, fat: 16 },
    dietary: { vegan: true, vegetarian: true, dairyFree: true },
    ingredients: ["chickpeas", "coconut milk", "tomato", "onion", "garam masala"],
    instructions: [
      "Sauté onion, garlic, spices.",
      "Add tomato and coconut milk; simmer.",
      "Stir in chickpeas; cook 10 min.",
    ],
    premium: false,
    allergens: [],
    notIncluded: ["Salt", "Oil"],
    utensils: ["Pot", "Wooden Spoon"],
    nutrientsExtra: { saturatedFat: 9, sugar: 10, fiber: 13, cholesterolMg: 0, sodiumMg: 540 },
  },
  {
    id: "beef-stir-fry",
    title: "Beef Veggie Stir-Fry",
    description:
      "Tender beef and colorful veggies in a savory sauce. Weeknight classic in 20.",
    time: 20,
    img: "https://images.unsplash.com/photo-1604908554007-86e8a3b43d71?q=80&w=1200&auto=format&fit=crop",
    tags: ["High Protein", "Dinner", "Quick"],
    cuisine: "Chinese",
    difficulty: "Easy",
    servings: 2,
    rating: 4.4,
    nutrients: { calories: 510, protein: 35, carbs: 34, fat: 26 },
    dietary: { highProtein: true },
    ingredients: ["beef", "broccoli", "bell pepper", "soy sauce", "garlic"],
    instructions: [
      "Marinate beef with soy sauce and garlic.",
      "Stir-fry beef, then vegetables; toss together.",
    ],
    premium: false,
    allergens: ["Soy"],
    notIncluded: ["Oil"],
    utensils: ["Wok", "Spatula"],
    nutrientsExtra: { saturatedFat: 9, sugar: 7, fiber: 5, cholesterolMg: 95, sodiumMg: 780 },
  },
  {
    id: "margherita-pizza",
    title: "Margherita Pizza",
    description:
      "Crispy crust with fresh mozzarella, basil, and tomatoes—simple Italian classic.",
    time: 30,
    img: "https://images.unsplash.com/photo-1541745537413-b804b0c33b29?q=80&w=1200&auto=format&fit=crop",
    tags: ["Vegetarian", "Dinner"],
    cuisine: "Italian",
    difficulty: "Medium",
    servings: 2,
    rating: 4.2,
    nutrients: { calories: 700, protein: 28, carbs: 88, fat: 24 },
    dietary: { vegetarian: true },
    ingredients: ["pizza dough", "mozzarella", "tomato", "basil"],
    instructions: [
      "Stretch dough, add sauce and cheese.",
      "Bake at high heat until bubbly; add basil.",
    ],
    premium: false,
    allergens: ["Milk", "Wheat"],
    notIncluded: ["Olive Oil"],
    utensils: ["Oven", "Baking Sheet"],
    nutrientsExtra: { saturatedFat: 12, sugar: 8, fiber: 4, cholesterolMg: 60, sodiumMg: 900 },
  },
  {
    id: "sushi-bowl",
    title: "Deconstructed Sushi Bowl",
    description:
      "All the sushi flavors in a quick weeknight bowl with salmon and rice.",
    time: 25,
    img: "https://images.unsplash.com/photo-1553621042-f6e147245754?q=80&w=1200&auto=format&fit=crop",
    tags: ["Pescatarian", "Lunch"],
    cuisine: "Japanese",
    difficulty: "Easy",
    servings: 2,
    rating: 4.6,
    nutrients: { calories: 520, protein: 30, carbs: 62, fat: 16 },
    dietary: { pescatarian: true },
    ingredients: ["rice", "salmon", "cucumber", "nori", "soy sauce"],
    instructions: [
      "Cook rice; flake cooked salmon.",
      "Assemble with sliced veg and nori; drizzle soy.",
    ],
    premium: false,
    allergens: ["Fish", "Soy"],
    notIncluded: ["Salt"],
    utensils: ["Pot", "Knife"],
    nutrientsExtra: { saturatedFat: 3, sugar: 8, fiber: 3, cholesterolMg: 55, sodiumMg: 700 },
  },
  {
    id: "quinoa-salad",
    title: "Mediterranean Quinoa Salad",
    description:
      "Fresh cucumbers, tomatoes, olives, and herbs tossed with protein-rich quinoa.",
    time: 15,
    img: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1200&auto=format&fit=crop",
    tags: ["Vegetarian", "Lunch", "Quick"],
    cuisine: "Mediterranean",
    difficulty: "Easy",
    servings: 2,
    rating: 4.1,
    nutrients: { calories: 380, protein: 12, carbs: 56, fat: 10 },
    dietary: { vegetarian: true, vegan: true },
    ingredients: ["quinoa", "cucumber", "tomato", "olive", "lemon"],
    instructions: [
      "Cook and cool quinoa.",
      "Toss with chopped veg, olives, lemon, and herbs.",
    ],
    premium: false,
    allergens: [],
    notIncluded: ["Salt", "Olive Oil"],
    utensils: ["Bowl", "Knife"],
    nutrientsExtra: { saturatedFat: 1, sugar: 4, fiber: 7, cholesterolMg: 0, sodiumMg: 420 },
  },
  {
    id: "tofu-scramble",
    title: "Spicy Tofu Scramble",
    description:
      "Vegan scramble with turmeric, peppers, and spinach—bright, savory breakfast.",
    time: 12,
    img: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=1200&auto=format&fit=crop",
    tags: ["Breakfast", "Vegan", "Quick"],
    cuisine: "American",
    difficulty: "Easy",
    servings: 2,
    rating: 4.0,
    nutrients: { calories: 260, protein: 20, carbs: 10, fat: 16 },
    dietary: { vegan: true, vegetarian: true, dairyFree: true, glutenFree: true },
    ingredients: ["tofu", "turmeric", "pepper", "spinach", "onion"],
    instructions: [
      "Crumble tofu; sauté with spices and veg until hot.",
    ],
    premium: false,
    allergens: ["Soy"],
    notIncluded: ["Salt", "Oil"],
    utensils: ["Skillet", "Spatula"],
    nutrientsExtra: { saturatedFat: 2, sugar: 3, fiber: 3, cholesterolMg: 0, sodiumMg: 340 },
  },
  {
    id: "shrimp-tacos",
    title: "Cilantro Lime Shrimp Tacos",
    description:
      "Zesty shrimp tucked in warm tortillas with crunchy slaw and lime crema.",
    time: 18,
    img: "https://images.unsplash.com/photo-1604908812838-43f7f2dfda7d?q=80&w=1200&auto=format&fit=crop",
    tags: ["Pescatarian", "Dinner", "Quick"],
    cuisine: "Mexican",
    difficulty: "Easy",
    servings: 2,
    rating: 4.5,
    nutrients: { calories: 480, protein: 28, carbs: 54, fat: 18 },
    dietary: { pescatarian: true },
    ingredients: ["shrimp", "tortillas", "cabbage", "cilantro", "lime"],
    instructions: [
      "Sear shrimp with spices; warm tortillas.",
      "Fill with slaw and shrimp; finish with lime crema.",
    ],
    premium: false,
    allergens: ["Shellfish", "Wheat"],
    notIncluded: ["Salt", "Oil"],
    utensils: ["Skillet", "Tongs"],
    nutrientsExtra: { saturatedFat: 4, sugar: 6, fiber: 4, cholesterolMg: 160, sodiumMg: 860 },
  },
  {
    id: "chicken-souvlaki",
    title: "Greek Chicken Souvlaki",
    description:
      "Herby marinated chicken skewers with lemony rice and tangy tzatziki.",
    time: 40,
    img: "https://images.unsplash.com/photo-1551218808-94e220e084d2?q=80&w=1200&auto=format&fit=crop",
    tags: ["High Protein", "Dinner"],
    cuisine: "Greek",
    difficulty: "Medium",
    servings: 3,
    rating: 4.7,
    nutrients: { calories: 610, protein: 44, carbs: 58, fat: 22 },
    dietary: { highProtein: true },
    ingredients: ["chicken", "yogurt", "garlic", "lemon", "oregano"],
    instructions: [
      "Marinate chicken; skewer and grill.",
      "Serve with rice and tzatziki.",
    ],
    premium: false,
    allergens: ["Milk"],
    notIncluded: ["Salt", "Olive Oil"],
    utensils: ["Grill Pan", "Skewers"],
    nutrientsExtra: { saturatedFat: 6, sugar: 4, fiber: 3, cholesterolMg: 130, sodiumMg: 780 },
  },
  {
    id: "thai-green-curry",
    title: "Thai Green Curry",
    description:
      "Fragrant green curry with coconut milk, chicken, and vegetables—spicy and cozy.",
    time: 35,
    img: "https://images.unsplash.com/photo-1604908177235-5b0d0f0fd5ab?q=80&w=1200&auto=format&fit=crop",
    tags: ["Dinner"],
    cuisine: "Thai",
    difficulty: "Medium",
    servings: 4,
    rating: 4.6,
    nutrients: { calories: 530, protein: 28, carbs: 40, fat: 28 },
    dietary: { dairyFree: true },
    ingredients: ["green curry paste", "coconut milk", "chicken", "bamboo", "basil"],
    instructions: [
      "Sauté curry paste; add coconut milk and aromatics.",
      "Simmer with chicken and vegetables.",
    ],
    premium: false,
    allergens: [],
    notIncluded: ["Salt"],
    utensils: ["Pot", "Knife"],
    nutrientsExtra: { saturatedFat: 16, sugar: 6, fiber: 4, cholesterolMg: 90, sodiumMg: 620 },
  },
  {
    id: "gluten-free-pancakes",
    title: "Fluffy Gluten-Free Pancakes",
    description:
      "Light and airy pancakes without gluten—perfect with maple and berries.",
    time: 20,
    img: "https://images.unsplash.com/photo-1508737804141-04ad2f277f2b?q=80&w=1200&auto=format&fit=crop",
    tags: ["Breakfast", "Kid-Friendly"],
    cuisine: "American",
    difficulty: "Easy",
    servings: 2,
    rating: 4.1,
    nutrients: { calories: 420, protein: 10, carbs: 68, fat: 12 },
    dietary: { glutenFree: true, kidFriendly: true },
    ingredients: ["gluten-free flour", "milk", "egg", "baking powder", "butter"],
    instructions: [
      "Mix batter; cook on griddle until golden.",
    ],
    premium: false,
    allergens: ["Milk", "Eggs"],
    notIncluded: ["Salt", "Oil"],
    utensils: ["Bowl", "Whisk", "Griddle"],
    nutrientsExtra: { saturatedFat: 5, sugar: 10, fiber: 2, cholesterolMg: 55, sodiumMg: 480 },
  },
  {
    id: "pecan-crusted-trout",
    title: "Pecan-Crusted Trout",
    description:
      "Steelhead trout fillets coated in honey mustard and a crunchy pecan-panko crust, served with apple-studded salad and thyme-roasted potatoes.",
    time: 35,
    img: "https://images.unsplash.com/photo-1528669826292-caad0837622d?q=80&w=1200&auto=format&fit=crop",
    tags: ["Dinner", "Premium"],
    cuisine: "American",
    difficulty: "Medium",
    servings: 2,
    rating: 4.8,
    nutrients: { calories: 960, protein: 31, carbs: 62, fat: 65 },
    dietary: { pescatarian: true },
    ingredients: [
      "0.06 oz Thyme",
      "1/2 oz Pecans (Contains: Tree Nuts)",
      "10 oz Steelhead Trout (Contains: Fish)",
      "1 Apple",
      "1/4 cup Panko Breadcrumbs (Contains: Wheat)",
      "2 oz Mixed Greens",
      "12 oz Potatoes",
      "1 Lemon",
      "2 tsp Honey",
      "2 tbsp Mayonnaise (Contains: Eggs)",
      "2 tsp Dijon Mustard",
    ],
    instructions: [
      "Roast sliced potatoes with thyme until crisp.",
      "Mix chopped pecans and panko; spread trout with honey-mayo-mustard and press in crust.",
      "Bake trout until flaky; toss greens with sliced apple and lemon dressing.",
      "Serve trout with potatoes and salad.",
    ],
    premium: true,
    allergens: ["Tree Nuts", "Fish", "Eggs", "Wheat", "Milk"],
    notIncluded: ["Olive Oil (2 tsp)", "Butter (2 tbsp) (Contains: Milk)", "Black Pepper", "Cooking Oil", "Salt"],
    utensils: ["Baking Sheet", "Medium Bowl", "Small Bowl", "Paper Towel", "Large Bowl"],
    nutrientsExtra: { saturatedFat: 18, sugar: 20, fiber: 7, cholesterolMg: 140, sodiumMg: 400 },
  },
];

export function getRecipeById(id: string) {
  return recipes.find((r) => r.id === id) || null;
}
